### ISSUE TITLE
Translate configuration preferences

### ISSUE THREAD

**Issue by ThibaudDauce** [wallabag/firefox-ext-v2#13]
Following https://github.com/ThibaudDauce/wallabag-firefox/commit/ea6d49907559af10087a909959d55efb51bc5c25, I need some german and polish speaking people to translate the new keys :-)

@benediktg and @bigretromike maybe?

- [x] polish
- [x] german

**Comment by bigretromike** [comment]
#14 here you go my good Sir

**Comment by ThibaudDauce** [comment]
Thanks again! :-)

**Comment by ThibaudDauce** [comment]
Thanks @benediktg!
