### ISSUE TITLE
Add a disconnect option

### ISSUE THREAD

**Issue by ThibaudDauce** [wallabag/firefox-ext-v2#15]
It could be nice to have a disconnect option (maybe with a right click on the wallabag icon if it's possible with the Firefox SDK)

**Comment by marsender** [comment]
Hi Thibaud,
Can you tell us how to disconnect ?
Thanks a lot for all your work !
Didier

**Comment by ThibaudDauce** [comment]
There is currently no way to disconnect. You can try by removing the credentials in your config…

**Comment by Simounet** [comment]
Closed because we won't fix it. This extension is deprecated in favour of [wallabagger](https://github.com/wallabag/wallabagger).
