### ISSUE TITLE
Use sdk/passwords instead of sdk/simple-storage

### ISSUE THREAD

**Issue by ThibaudDauce** [wallabag/firefox-ext-v2#18]
Mozilla refuse to review the addon because passwords and authorization tokens should be saved using sdk/passwords, not sdk/simple-storage.

I looked the documentation (https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/passwords) but the API is really awful with a callback to search for the access token. If someone see how to solve this issue… I don't understand how to check for the presence of access token in sync. 

Thanks for the help

**Comment by ThibaudDauce** [comment]
Do we need to use these kind of search function
```javascript
function show_my_addon_passwords() {
  require("sdk/passwords").search({
    url: require("sdk/self").uri,
    onComplete: function onComplete(credentials) {
      credentials.forEach(function(credential) {
        console.log(credential.username);
        console.log(credential.password);
        });
      }
    });
  }
```

Or a simpler one like this one
```javascript
function show_passwords_for_joe() {
  require("sdk/passwords").search({
    username: "joe",
    onComplete: function onComplete(credentials) {
      credentials.forEach(function(credential) {
        console.log(credential.username);
        console.log(credential.password);
        });
      }
    });
  }
```

What's the username for us? Do I add a key `type` with the value `access_token`? Do I set both access_token and refresh_token in the same password object?

**Comment by jlnostr** [comment]
Maybe you could save the access token as username and the refresh token as password. Username and password should be only used once for the login.

**Comment by bigretromike** [comment]
@jlnostr I think that its because wallabag enforce this because API use same user/password/token/secret , but yeah that is bad
