### ISSUE TITLE
Add lang switch dropbox

### ISSUE THREAD

**Issue by bigretromike** [wallabag/firefox-ext-v2#19]
Could you add language selector?

**Comment by ThibaudDauce** [comment]
I think the lang is based on your Firefox lang…

**Comment by bigretromike** [comment]
which is not correct all the time. For example newest nightly builds are in english so I cannot see Polish translation that I provided :+1:

**Comment by ThibaudDauce** [comment]
It seems to be a problem to fix with Firefox nightly builds and not with the extension.

But if you find a way to add a language selector to the extension, please send me a link and I'll look at it.

**Comment by bigretromike** [comment]
I wouldn't say its issue because it work intention, I would like to use En Firefox with PL plugin :+1:

**Comment by Simounet** [comment]
Closed because we won't fix it. This extension is deprecated in favour of [wallabagger](https://github.com/wallabag/wallabagger).
