### ISSUE TITLE
An error occured during saving the article.

### ISSUE THREAD

**Issue by steckerhalter** [wallabag/firefox-ext-v2#20]
So I have installed the extension, generated the client id/secret and entered them in the settings. Then upon saving I entered my username/password and I get `An error occured during saving the article.`

On the webserver I see a 401, so the authorization doesn't work for some reason?

Wallabag is version 2.0.4

**Comment by ThibaudDauce** [comment]
Could you go to `about:config` and add a new key: `extensions.@wallabag-v2.sdk.console.logLevel` with the value `all`.

Maybe restart your Firefox. Then open the developer console (Ctrl-Shift-J on my computer) 
and filter the logs with the search bar (search for "wallabag"). Could you send me the result 
after trying to connect?

**Comment by steckerhalter** [comment]
I tried this but I get no output. Is the console tab the right one?

**Comment by ThibaudDauce** [comment]
I'm not sure… I think the console tab and the developer console are different…

**Comment by steckerhalter** [comment]
```
wallabag-v2:wallabag server is ready! I can post! index.js:97
wallabag-v2:"I'm gonna add https://github.com/wallabag/firefox-ext-v2/issues/20#issuecomment-220354076 on the https://save.datenpark.ch/api/entries!" server.js:16
wallabag-v2:Impossible to save the article. index.js:126
wallabag-v2:Object { error: "access_denied", error_description: "OAuth2 authentication required" } index.js:127
```

**Comment by ThibaudDauce** [comment]
I don't understand why it's failing… Have you tried creating new clients and new secrets and change in the config? And to uninstall / reinstall the addon?

**Comment by steckerhalter** [comment]
Yes, I did all of that multiple times even. I haven't got the time to look into it more closely now. I'll check later if it works with another setup.

**Comment by ThibaudDauce** [comment]
Did you manage to save an article?

**Comment by steckerhalter** [comment]
With the firefox extension? No

**Comment by ThibaudDauce** [comment]
Really weird :-(

Do you have in the developer menu "refresh_token" as grant type allowed for your client? 

Could you try to make HTTP requests by hand following this post https://www.wallabag.org/blog/2015/10/06/developers-oauth2?

**Comment by steckerhalter** [comment]
I kid you not. I went through the manual requests and got that working and now after having installed the firefox extension it suddenly works (I even used the previous tokens...)

**Comment by ThibaudDauce** [comment]
That's weird…

So, could I close this issue?

**Comment by steckerhalter** [comment]
I'll do, thanks for developing wallabag!

**Comment by theslash** [comment]
Hi, can you tell me what you did? I have the same problem but can't get it to work...

**Comment by steckerhalter** [comment]
@theslash I followed https://www.wallabag.org/blog/2015/10/06/developers-oauth2 and after that it suddenly worked...

**Comment by theslash** [comment]
Ok...I tried this already. thanks anyway!!
