### ISSUE TITLE
Being able to tag a page upon being wallabaged

### ISSUE THREAD

**Issue by bmillemathias** [wallabag/firefox-ext-v2#21]
I often want to add some tag to a page I've just wallabaged, it'd be nice to permit such action in the workflow.

Thanks for this extension.

**Comment by ThibaudDauce** [comment]
Unfortunately, it's not yet possible to do that with the current wallabag API :-(

But it's planned, that why the panel stay open after saving the article, I wanted to add an input to add tags.

**Comment by anarcat** [comment]
the wallabag API supports tagging now, i believe - the chrome plugin does it. could this be added as well?

consider how issues came up when implementing this in the chrome plugin, however, in terms of usability: https://github.com/wallabag/wallabagger/issues/16

**Comment by Rurik19** [comment]
@anarcat meanwhile: wallabagger is awaiting mozilla store approvement to be real firefox extension :-)

**Comment by ThibaudDauce** [comment]
As soon as the https://github.com/wallabag/wallabagger extension gets the Mozilla store approval, I will deprecate this extension to focus on the unify Chrome / Firefox one :-)

**Comment by anarcat** [comment]
cool, let us know! :)

**Comment by anarcat** [comment]
i see the extension here: https://addons.mozilla.org/en-US/firefox/addon/wallabagger/

.... but it says it doesn't work with firefox 45 - is that normal?

seems to work in firefox 50 though, thanks!

shouldn't this be officially deprecated now?

**Comment by Simounet** [comment]
Closed because we won't fix it. This extension is deprecated in favour of [wallabagger](https://github.com/wallabag/wallabagger).
