### ISSUE TITLE
support firefox for android

### ISSUE THREAD

**Issue by oksijun** [wallabag/firefox-ext-v2#22]
I was able to install this extension on android but the options are inaccessible, so it can't be used.
Any chance this could be fixed ?

**Comment by benediktg** [comment]
When you have installed the wallabag app for Android you are able to select "bag it" in the share menu. Hence there is no need for Android support by this extension in my opinion.

**Comment by oksijun** [comment]
Yes, thanks, I missed that - sorry for the noise.

**Comment by ThibaudDauce** [comment]
No problem!
