### ISSUE TITLE
Button indicate state of page 

### ISSUE THREAD

**Issue by bigretromike** [wallabag/firefox-ext-v2#24]
Button act like the pocket one, you see if its added or not
This could be done via caching locally all pages added. So you find url in that database and see if its there or not this also include the #23 so you could remove it

**Comment by ThibaudDauce** [comment]
It could be a great feature but maybe we should wait for the API endpoint https://github.com/wallabag/wallabag/issues/1796 to check the server database instead of the local one?

**Comment by bigretromike** [comment]
yup thats an option, i propose local one because of not having that for api :-)
But also I want point out that this great plugin miss this little useful functionality

**Comment by ThibaudDauce** [comment]
We really need to fix #18 before, Firefox refuse any upgrade if this is not done…

**Comment by ThibaudDauce** [comment]
PR https://github.com/wallabag/wallabag/pull/2325 is merged so we can work on this feature!

It will only work with the new version of wallabag (v2.1 I think) and we need to check for a 404 (for v2.0 installations) and do nothing.

We also need to add a new black wallabag icon to show when the page is already booked.

**Comment by bigretromike** [comment]
Sound like a good plan :-)


On October 2, 2016 6:43:57 PM GMT+02:00, Thibaud Dauce <notifications@github.com> wrote:
>PR https://github.com/wallabag/wallabag/pull/2325 is merged so we can
>work on this feature!
>
>It will only work with the new version of wallabag (v2.1 I think) and
>we need to check for a 404 (for v2.0 installations) and do nothing.
>
>We also need to add a new black wallabag icon to show when the page is
>already booked.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/wallabag/firefox-ext-v2/issues/24#issuecomment-250980981

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Simounet** [comment]
Closed because we won't fix it. This extension is deprecated in favour of [wallabagger](https://github.com/wallabag/wallabagger).
