### ISSUE TITLE
Support HTTP Basic Auth

### ISSUE THREAD

**Issue by grote** [wallabag/firefox-ext-v2#25]
My wallabag instance is behind HTTP Basic Authentication and the Android app supports it. Unfortunately, this add-on doesn't, so I can't use it with my instance. Would be great if this would be added.

If trying to connect I just get the message: `Impossible to connect.`

**Comment by ThibaudDauce** [comment]
Yes it could be nice!

Not a lot of time right now to work on the add-on… And #18 is required before any other change :-( (Firefox refuse upgrades if it's not done)

**Comment by Simounet** [comment]
Closed because we won't fix it. This extension is deprecated in favour of [wallabagger](https://github.com/wallabag/wallabagger).
