### ISSUE TITLE
OAuth2 authentication not successfull

### ISSUE THREAD

**Issue by theslash** [wallabag/firefox-ext-v2#27]
Hi
I got to this problem using the Firefox Plugin.
When I enter my Username & Password it always says "Error saving the Article" (In German ;-)

So I tried the suggestions here:
https://www.wallabag.org/blog/2015/10/06/developers-oauth2

I get this response:

Cache-Control: no-store, private
Content-Type: application/json
Date: Thu, 25 Aug 2016 08:01:04 GMT
Pragma: no-cache
Server: Apache
Transfer-Encoding: chunked
X-Powered-By: PHP/5.5.9-1ubuntu4.17
X-Powered-By: PleskLin

{
    "access_token": "ODEzM2VkZDlmMGFkMGZhODE4M2M1OGI1OGU4Y2JiYTNjZDhjZGRlOTI4ZGRhOTdhMjE5MGY3NmM5YjcxNzMxOA",
    "expires_in": 3600,
    "refresh_token": "Yjg4MGE2NmY3MjkwMDVmNTQ0MTliNGZjODRhNThhNjA0YzcyNGMyOTY5ZTkzYzAyNTIyMDczNWU4YzJmMTQwNg",
    "scope": null,
    "token_type": "bearer"
}

But when I continure with this:

http` GET http://address.de/api/entries.json \
    "Authorization:Bearer ODEzM2VkZDlmMGFkMGZhODE4M2M1OGI1OGU4Y2JiYTNjZDhjZGRlOTI4ZGRhOTdhMjE5MGY3NmM5YjcxNzMxOA"

I just get this response:

HTTP/1.1 401 Unauthorized
Cache-Control: no-store, private
Content-Type: application/json
Date: Thu, 25 Aug 2016 08:08:40 GMT
Pragma: no-cache
Server: Apache
Transfer-Encoding: chunked
WWW-Authenticate: Bearer realm="Service", error="access_denied", error_description="OAuth2 authentication required"
X-Powered-By: PHP/5.5.9-1ubuntu4.17
X-Powered-By: PleskLin

{
    "error": "access_denied",
    "error_description": "OAuth2 authentication required"
}

**Comment by Simounet** [comment]
Hi,
Which version of wallabag and addon are you using?
Did it ever worked?

**Comment by Simounet** [comment]
Closed because we won't fix it. This extension is deprecated in favour of [wallabagger](https://github.com/wallabag/wallabagger).
