### ISSUE TITLE
0.0.10 repeatedly asking for credentials

### ISSUE THREAD

**Issue by markwaters** [wallabag/firefox-ext-v2#29]
Recently my Firefox (49.0b1) silently upgraded me from version 0.0.8 to 0.0.10 and immediately I started seeing the credentials box repeatedly pop-up , also more-often-than-not clicking on the toolbar icon did not actually save the article.

I had to check each article in the unread section of wallabag and add it manually if missing.

Today I switched back to version 0.0.8 and everything appears to be working correctly again (no credentials box and articles are saved every time).

Anyone else seeing this ?

**Comment by phofm** [comment]
I had the same issue with Firefox (48.0.1) which upgraded to version 0.0.10 yesterday.

Thanks to your suggestion, @markwaters, I downgraded to 0.0.8 and it appears to be working as expected, again.

**Comment by ThibaudDauce** [comment]
I have the same problem, maybe @Simounet can look at it?

**Comment by markwaters** [comment]
@phofm glad to discover it's a bug and that rolling back fixed it for us all , fingers crossed for a fix.

**Comment by ThibaudDauce** [comment]
Some logs for @Simounet 

```
wallabag-v2:wallabag server is ready! I can post!index.js:108
wallabag-v2:"I'm gonna add https://www.google.fr/?gfe_rd=cr&ei=hQ_RV6_TEISx8we5roPQDg&gws_rd=ssl on the https://read.hadibut.fr/api/entries!"server.js:16
wallabag-v2:Access token expired. Trying to refresh with 1_3oh6t6wnjla88cs0k8gssc0skc00g40ggwcg4cw0sw4g8kwoo8 and 4s8z1j7yr5ico8so4wwoc0go4cg4cosoow0ogk4oggog0ock04index.js:123
wallabag-v2:Object {  }connection.js:66
wallabag-v2:Object { access_token: "NzgzNTkyMTEzYmVhZWQ1YjQ2ZjkxNjI5OWF…", expires_in: 3600, token_type: "bearer", scope: null, refresh_token: "NTZkYzI4OTE0YmQyNWIwYjgxZmMxN2ZhZjk…" }index.js:125
A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Thu Sep 08 2016 09:13:14 GMT+0200 (CEST)
Full Message: ReferenceError: wallabag is not defined
Full Stack: handleChange/</<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://wallabag-v2/index.js:126:13
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:937:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:816:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:750:11
index.js:126
```

It seems `wallabag` is undefined in `index.js:126`.

**Comment by ThibaudDauce** [comment]
Can someone test master? I push 5d557c9781bfb921dde6675398c439b85965df3f which replace the `wallabag` by `wallabag_server`.

**Comment by ThibaudDauce** [comment]
It seems to work but I still have an error when refreshing: "Error: This login already exists."
I think we need to remove the credential before storing the new one. We need a fusion of the two examples bellow:

```js
require("sdk/passwords").search({
  username: "joe",
  onComplete: function onComplete(credentials) {
    credentials.forEach(require("sdk/passwords").remove);
  })
});

require("sdk/passwords").remove({
  realm: "User Registration",
  username: "joe",
  password: "SeCrEt123"
  onComplete: function onComplete() {
    require("sdk/passwords").store({
      realm: "User Registration",
      username: "joe",
      password: "{new password}"
    })
  }
});
```

**Comment by Simounet** [comment]
Sorry I was far from home. I will look into this.

**Comment by ThibaudDauce** [comment]
No problem, thank you!

**Comment by Simounet** [comment]
Every time the token expired, we had to login again but the new token can't be stored to Firefox because of the existing one. I decided to remove credentials on token expiration. Can you try it please?

**Comment by ThibaudDauce** [comment]
It's working for me! Can you open a PR please?

**Comment by Simounet** [comment]
Done.

**Comment by ThibaudDauce** [comment]
@markwaters @phofm The version 0.0.11 is out with a fix. Could you test and report any problem?

**Comment by markwaters** [comment]
Thanks @ThibaudDauce , I have installed the new 0.0.11 version of the plugin on a new firefox installation and its working perfectly , I will update my old installation later and report back.

**Comment by ThibaudDauce** [comment]
Thanks for your report! :-)

**Comment by loomchild** [comment]
I confirm, it works perfectly. Thanks a lot for fixing it!

**Comment by markwaters** [comment]
Regarding my 'old' installation , I have upgraded and it still repeatedly asks for credentials.
I have removed the plugin and will install again.

**Comment by ThibaudDauce** [comment]
That's weird…

Could you try to go to `about:debugging`,click on "Debug" near the wallabag module, and send us some logs?

**Comment by markwaters** [comment]
Removed the plugin , restarted Firefox , reinstalled the plugin.
I didn't have to enter the client id and client secret as those fields were already populated correctly.
I am still asked for my username and password , not everytime I save an article but certainly more than once , perhaps twice in 24 hours.
I have tried enabling the debug mode for the logs but nothing happens in the console window when I save an article , sorry but I have never used this debugging thing before.

**Comment by ThibaudDauce** [comment]
No problem… I don't really understand why it doesn't work with you…

Have you try refreshing your tokens? Deleting them and creating new ones?

**Comment by markwaters** [comment]
I haven't tried that as I am using the same tokens on the other newly setup Firefox installation (Netbook) without any problems.
This issue seems to be confined to the old installation (Desktop).

**Comment by markwaters** [comment]
Where is the wallabag plugin data stored ?
Perhaps deleting that and reinstalling would fix it ?
Could something be left behind from the initial install ?

**Comment by Simounet** [comment]
It's in the `Saved Logins` under `about:preferences#security`.

**Comment by markwaters** [comment]
Thanks , I have removed all instances of the wallabag credentials and reinstalled the plugin.
I'll tell you hown its going in a few days time after I have saved a few more articles.
Thanks @Simounet

**Comment by Simounet** [comment]
@markwaters Hi, is that ok for you? Can I close this issue?

**Comment by markwaters** [comment]
Sure , but I do get asked fro credentials every two weeks or so , both on the old and new installations of the plugin.
Is this normal ?
I would have thought that as this is saved in Firefox I would never be asked again unless the password was changed on the server.

**Comment by Simounet** [comment]
I don't think this is normal. Are you adding new content often? I'm not so aware of the token refresh but I think it should be transparent for you, without entering your infos.

**Comment by markwaters** [comment]
I use wallabag and the firefox plugin almost everyday.
Nowadays I prefer reading pages in wallabag than the actual website plus it also acts as a bookmark so I can go and find the article again later.
Now I know this is unexpected behaviour I will keep a record of when it asks me for the credentials.
