### ISSUE TITLE
Compatibile with 2.1.1

### ISSUE THREAD

**Issue by bigretromike** [wallabag/firefox-ext-v2#32]
After updating to 2.1.1 whenever I click on button window pop up with unreaded articles instead of adding article to database.

**Comment by Simounet** [comment]
Hmmm, I have not encountered any issue by now with 2.1.1. What's your Firefox extension version? Can I have a screenshot please?

**Comment by bigretromike** [comment]
extension version is 2.0.0
firefox is 49.0.1
the only thing I enter to extension was https://wallabag.mydomain

**Comment by Simounet** [comment]
I'm a little bit confused. We are on the version 0.0.11 of this extension right now.
Are you using https://addons.mozilla.org/fr/firefox/addon/wallabag-v2/ or this one https://addons.mozilla.org/fr/firefox/addon/wallabag/?

**Comment by bigretromike** [comment]
Ok, looks I missclicked proper version and install the old one. Sorry - my fault, but when I was searching for wallabag this one came up

**Comment by Simounet** [comment]
We get it and renamed the old extension to be more clear. Don't worry and have a nice day!
