### ISSUE TITLE
extension works on chrome but not on firefox

### ISSUE THREAD

**Issue by persianphilosopher** [wallabag/firefox-ext-v2#33]
Hello,

I have installed wallabag (2.1.1) on my server and have set up the client id and secret. On chrome, "wallabagit" says that there is a problem with the api but it actually works and is able to save articles etc.

On firefox, using wallabag v2 (0.0.11), I can enter all the information in the settings. When I click on the button, it asks me to login but returns "impossible to connect" as message. I have uninstalled and reinstalled etc, but it does not allow me to login no matter what. 

I don't know if there is a FF log anywhere I can find for you but wanted to report the issue. Thank you

**Comment by Simounet** [comment]
Hi,
Do you have any error on the wallabag logs? You can try to clean your Firefox extension settings through `Saved Logins` under `about:preferences#security` with the site `addon:@wallabag-v2 (Api Tokens)`.

**Comment by persianphilosopher** [comment]
Unfortunately that did not solve the problem. I looked for a log but I could not find one. Is there a particular log and place you have in mind? Thank you

**Comment by yvesle** [comment]
I had to uninstall/reinstall to even see the button.
After that I had the same problem. I could not find the entry `addon:@wallabag-v2 (Api Tokens)` in the saved password. 
Using 49.0.1 on Windows 7. I use a master password.

**Comment by Simounet** [comment]
Hi there,
Sorry for the late reply. If you want to check the debug lines, you have to follow these steps:
- Go to `about:config` then validate the warning message
- Right click on the list
- `New` > `String`
- name: `extensions.@wallabag-v2.sdk.console.logLevel`
- value: `all`
- Restart Firefox
- Go to `about:debugging#addons`
- Check the activation box
- Debug on wallabag v2
- Agree with the message

You must see something like this on the console tab:

`wallabag-v2:"http://mywallabag.com" 1_ybmioodalokndakndalknfnawkc0c00ggw ypojadbnfbabdaobdaoibdbbd040c undefined undefined true`

**Comment by persianphilosopher** [comment]
Thank you. I followed your steps and it is as you described:
"xxx" 1_2u2pksbrmjuok4ko0wckk48c0wkksck4k44kk0kgoo844c84sg 4ngd8ymnu1a8k8c4sow4g04w4coggcwgk80kc0ok0kgk4w0scs undefined undefined true
(Not sure if I should include the actual url here publicly but let me know if that is needed).  That was on configuration: 54
The rest is repeating this pattern:
wallabag-v2:wallabag server undefined, checking configuration…index.js:72
wallabag-v2:Connection error:connection.js:24

**Comment by Simounet** [comment]
Can you try to use this extension on a clean Firefox profile?

**Comment by Simounet** [comment]
Closed because we won't fix it. This extension is deprecated in favour of [wallabagger](https://github.com/wallabag/wallabagger).
