### ISSUE TITLE
Can't authenticate to wallabag

### ISSUE THREAD

**Issue by dbeniamine** [wallabag/firefox-ext-v2#36]
Hello,

I just installed wallabag 2.0.5 on my server (debian jessie, apache 2.4.10) and the firefox extension on my laptop.
I create a client from the developper tab and set the plugin as explained.
When I click on the "w" button it asks me to login to my wallabag but once i click on the "connect" button, nothing happens.

I started firefox from the console and get this output after trying to connect my wallabag:

    console.error: wallabag-v2: 
      Message: TypeError: response is null
      Stack:
        create_panel/</<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://wallabag-v2/connection.js:21:11
    connect/<.onComplete@resource://gre/modules/commonjs/toolkit/loader.js -> resource://wallabag-v2/connection.js:46:11
    emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
    emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
    onreadystatechange@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/request.js:104:7
    
    1481393310174	addons.productaddons	ERROR	Request failed certificate checks: [Exception... "SSL is required and URI scheme is not https."  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: resource://gre/modules/CertUtils.jsm :: checkCert :: line 145"  data: no]

My server is indeed accessible only by https, but the url I provided to the plugin uses the https protocol and my certificate is trusted (let's encrypt certificate), but actually I'm not sure if the last line comes from wallabag addon or another one.

Edit: I confirm that the last line of the log has nothing to do with wallabag addon.

**Comment by Simounet** [comment]
Hi David,
Don't have any warning when you try to login from the web page? Can you try to check the debug with `about:debugging#addons` just to be sure?

I don't think this is related to your problem but Wallabag 2.1.5 is out, by the way.

**Comment by dbeniamine** [comment]
I don't know why but nothing happens when I click "debug" on any addon ...

I have no warning on the web interface login, but I think I found the issue by looking at the apache logs.
There are the server log of two login, the first three lines comes from a web interface login, the two last from the addon:

    [10/Dec/2016:19:38:28 +0100] "POST /wallabag/app.php/login_check HTTP/1.1" 302 1095 "https://my_server.dtdns.net/wallabag/app.php/login" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
    [10/Dec/2016:19:38:29 +0100] "GET /wallabag/app.php/ HTTP/1.1" 200 4102 "https://my_server.dtdns.net/wallabag/app.php/login" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
    [10/Dec/2016:19:38:29 +0100] "GET /wallabag/bundles/wallabagcore/themes/material/img/logo-square.png HTTP/1.1" 200 3841 "https://my_server.dtdns.net/wallabag/app.php/" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
    
    [10/Dec/2016:19:38:51 +0100] "POST /wallabag/oauth/v2/token HTTP/1.1" 302 738 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
    [10/Dec/2016:19:38:51 +0100] "GET /wallabag/app.php HTTP/1.1" 200 4102 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0

It seems that the addon is redirected to `/wallabag/app.php` instead of  `/wallabag/app.php/oauth/v2/token` ...
Changing the url on the addon configuration to `https://my_server.dtdns.net/wallabag/app.php` fixes the issue, but it is ugly ...

I think that the issue comes from my rewrite rule on my apache2 configuration file for wallabag which is:

    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ https://%{SERVER_NAME}/wallabag/app.php [QSA,L]

I don't have the time right now to find the good rewrite rule, I'll take a look tomorrow and post my solution here in case someone else have the same issue.

Concerning the new version of wallabag, I know but I think there are some dependencies issues with debian jessie, I'll try to do the update once I have more time ...

**Comment by Simounet** [comment]
Ok, no problem. I'm closing this issue but please, let us know your solution.
Have a nice week-end.

**Comment by dbeniamine** [comment]
So just in case someone have the same issue, the correct rewrite rule for having wallabag in an apache virtual directory (/wallabag in my case) is:

    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ /wallabag/app.php [QSA,L]

**Comment by Simounet** [comment]
Thank you so much!

**Comment by dbeniamine** [comment]
You're welcome, thanks for your work on the wallabag plugin :)
