### ISSUE TITLE
Icon disappears when setting Firefox to "don't save history" mode

### ISSUE THREAD

**Issue by rabyte** [wallabag/firefox-ext-v2#37]
Hi,

whenever I use this setting under settings->privacy->history->firefox will create a history: NEVER
my wallabag icon will disappear after a Firefox restart. (Basically this is the "privacy always on" mode).

![grafik](https://cloud.githubusercontent.com/assets/7279277/21286612/8a307b14-c459-11e6-88db-e1c9962acf81.png)

I can still find it in the settings "customize symbols" ![grafik](https://cloud.githubusercontent.com/assets/7279277/21286622/b6bf425a-c459-11e6-8368-110d4a0aad1e.png) , but without a picture

![grafik](https://cloud.githubusercontent.com/assets/7279277/21286649/0d35db76-c45a-11e6-9d4c-261f9d65b43a.png)

Any idea why this would happen?
When I set "create history" back to standard, the icon shows up again.

(I am using wallabag 2.1.5 and Firefox 50.1.0)

**Comment by Simounet** [comment]
Hi,
I think my last commit should fix this issue.
