### ISSUE TITLE
May record the wrong page

### ISSUE THREAD

**Issue by romu70** [wallabag/firefox-ext-v2#38]
Hello,
I self-host Wallabag on my own server behind my ADSL line. With ADSL, download from my wallabag is the worst case of course (a bit less than 1Mb/s).

Here is a simple test case which records the wrong page in Wallabag with the Firefox extension.

Pre-conditions: you've 2 tabs opened in Firefox, let's call them T1 and T2.

1. T1 is you currently displayed tab and you click on the wallabag button
-> you get the message "the article is being saved...."
2. Then, make your T2 active.

If you didn't wait the wallabag saving to complete before switching from your Firefox tab, there is a great chance your saved T2 instead of T1.

**Comment by Simounet** [comment]
Closed because we won't fix it. This extension is deprecated in favour of [wallabagger](https://github.com/wallabag/wallabagger).
